@startuml
TestWrapper -> SourceProcessor: parseProgram(string filePath)
activate SourceProcessor

SourceProcessor -> Parser: parseProgram(string filePath)
activate Parser

Parser --> SourceProcessor
deactivate Parser

SourceProcessor -> Parser: getParsedProgram()
activate Parser

Parser --> SourceProcessor
deactivate Parser

SourceProcessor -> Tokeniser: feedLines(vector<string> lines)
activate Tokeniser

Tokeniser --> SourceProcessor
deactivate Tokeniser

SourceProcessor -> Extractor: extract(vector<Line> extractedLines)
activate Extractor

SourceProcessor <-- Extractor
deactivate Extractor

TestWrapper <-- SourceProcessor
deactivate SourceProcessor



TestWrapper -> SourceProcessor: storeDataInPKB(PKB pkb)
activate SourceProcessor

SourceProcessor -> Extractor: getProcedures(), getVariables(), getConstants(), ...
activate Extractor

SourceProcessor <-- Extractor: set<string> procNames, set<string> varNames, ...Extractor
deactivate Extractor

SourceProcessor -> ProgramKnowledgeBase: addAllProcs(set<string> procNames), addAllConstants(set<string> constVals), ...
activate ProgramKnowledgeBase

SourceProcessor <-- ProgramKnowledgeBase
deactivate ProgramKnowledgeBase


TestWrapper <-- SourceProcessor
deactivate SourceProcessor
@enduml